project tools update
git-svn-id: file:///source/coreland/corelib/trunk@2251 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/mk-systype b/mk-systype
--- a/mk-systype
+++ b/mk-systype
@@ -147,7 +147,7 @@ fi
 ./_mk_systype
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not create _mk_systype" 1>&2
+  echo "fatal: could not execute _mk_systype" 1>&2
   cleanup
   exit 1
 fi
